### ISSUE TITLE
Add possibility to activate any perfSONAR repo inside the container

### ISSUE THREAD

**Issue by tonin** [perfsonar/docker-devbox#8]
It would be nice to be able to easily activate a perfSONAR repository (nightly or whatever else) from a configuration step or from the `prep-steps-user.m4` file.  I guess all the steps could be put in that file (would need to review the M4 syntax), but maybe a function similar to the `install_pkg` would help.

**Comment by tonin** [comment]
@mfeit-internet2 Could this be done via the `libexec/prep/prep-steps-user.m4` file but with a different set of instructions depending on the base box being defined?

Let's say that in `etc/bases` I declare the following:
```
d11-ps debian:11
d11-ps-snapshot debian:11
```

How could I use that in `libexec/prep/prep-steps-user.m4` to install a different pS repository based on the image name?  I.e.: the release repo for the first one and the snapshot repo for the second one?

**Comment by mfeit-internet2** [comment]
I think the right way to solve this would be [Unibuild-style user-definable variables](https://github.com/perfsonar/unibuild#user-defined-macros) that can be passed into `build` and brought into the container when prep is done, e.g.:

```
ddb build --define DEBIAN_REPO_FLAVOR=snapshot d11
```

Since `bases` is a shorthand for things that are fed to `build`, we could also make `build` grab arguments from there as well:

```
d11-ps debian:11
d11-ps-snapshot debian:11 DEBIAN_REPO_FLAVOR=snapshot FOO=bar BAZ=quux
```

In both cases, that would make the additional macros available to `prep` for decision making.

Will that work for you?

**Comment by mfeit-internet2** [comment]
I went ahead and made those changes because I thought they'd be useful.  You can find the changes in the `issue-8` branch if you want to try them out.  Take note of the changes in the documentation, especially that macro names are preceded by a double underscore (e.g., `__FOO`).

**Comment by mfeit-internet2** [comment]
This has been merged.  Let me know if you need anything else.
